import SideNav from "@/components/staff/SideNav";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function StaffLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <aside>
          <SideNav />
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
